# -*- coding: utf-8 -*-
"""Entrega Programacion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-bkfZLRut02zr8ZWR6tyGihHm5jO4gXI
"""

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/

ls

!pip install gspread
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

import pandas as pd
import warnings
from datetime import date
import matplotlib.pyplot as plt                 ## Módulo para graficar
import seaborn as sns

pd.set_option('display.max_columns', None)
df_icfes = pd.read_csv('Saber_11_2019-2.csv')
df_icfes.head()

import folium
Geo_json_barrios_Bogota = "https://raw.githubusercontent.com/Juan-Salazar-Saenz/Geo/master/ordenes_nuevo.json" 
m = folium.Map(location=[4.6214113,-74.0198998], zoom_start=10) 
folium.Choropleth(
    geo_data=Geo_json_barrios_Bogota,
    name="choropleth",
    data=None,
    columns= None,
    key_on= None,
    fill_opacity=0.7,
    line_opacity= 0.2,
    legend_name="emisiones por kt C02 ",
).add_to(m)
m

Geo_json_barrios_Bogota.__len__()

df_bogota = df_icfes[df_icfes['ESTU_DEPTO_RESIDE'] == 'BOGOTÁ']
df_bogota.head()

pd.set_option('display.max_columns', None)
df_colegio_col = pd.read_csv('Colegio colombia.csv',encoding='latin-1',index_col=False)
df_colegio_col.head(1)

df_colegio_bog = df_colegio_col[df_colegio_col['NOMBRE_MUNICIPIO'] == 'BOGOTA D.C.']
df_colegio_bog.head()

new_df = pd.merge(df_bogota[["ESTU_CONSECUTIVO", "COLE_COD_DANE_ESTABLECIMIENTO"]], df_colegio_bog[["COD_COL", "NOM_COL", "LATITUD", "LONGITUD","NOMBRE_MUNICIPIO"]],  how='inner', left_on=['COLE_COD_DANE_ESTABLECIMIENTO'], right_on = ['COD_COL'])
new_df.head()

new_df.__len__()

df_sin_duplicados = new_df.drop_duplicates(subset=['COD_COL'])

df_sin_duplicados.__len__()

df_sin_duplicados.head()

from decimal import Decimal
def acomodar(x):
  X = x.replace(',','.')  
  return Decimal(X)
df_sin_duplicados['LATITUD'] = df_sin_duplicados.apply(lambda x: acomodar(str(x[4])),axis=1,result_type='expand') 
df_sin_duplicados['LONGITUD'] = df_sin_duplicados.apply(lambda x: acomodar(str(x[5])),axis=1,result_type='expand') 

#print(acomodar(df_sin_duplicados.iloc[0]))

df_sin_duplicados.head()

df_sin_duplicados.dtypes

df_clean = df_sin_duplicados.dropna(subset=["LATITUD", "LONGITUD"])

tooltip = "Click me!"
# Agregar los marcadores
for index, colegio in df_clean.iterrows():
    latitud = colegio["LATITUD"]
    longitud = colegio["LONGITUD"]
    folium.Marker([latitud, longitud], popup="<i>Mt. Hood Meadows</i>", tooltip=tooltip).add_to(m)

# Mostrar el mapa
m