# -*- coding: utf-8 -*-
"""json con pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AmMGtVnXhfwdYotRXQkJ4oUQBc05-jys
"""

import pandas as pd
import folium
import json

codigo_localidad=[]
codigo_upz=[]
codigo_barrio=[]
nombre=[]
geo_shape=[]

archivo_json = "barrios-bogota.json"  # Reemplaza con la ruta a tu archivo JSON

with open(archivo_json, 'r') as f:
    datos_json = json.load(f)
    for feature in datos_json:
      codigo_localidad.append(feature['codigo_localidad'])
      codigo_upz.append(feature['codigo_upz'])
      codigo_barrio.append(feature['codigo_barrio'])
      nombre.append(feature['nombre'])
      geo_shape.append(feature['geo_shape']['geometry'])
      #geo_shape.append(feature['geo_shape']['geometry']['coordinates'])

datos = {'codigo_localidad':codigo_localidad,
         'nombre':nombre,
         'codigo_upz':codigo_upz,
         'codigo_barrio':codigo_barrio,
         'geo_shape':geo_shape,}
datos_df = pd.DataFrame(datos)

datos_df.columns

print(datos_df.iloc[1])

print(geo_shape.__len__())

datos_df['geo_shape'].iloc[1]

json_A = {}
json_A['type'] = 'FeatureCollection'
json_A['features'] = []

for geo in range(geo_shape.__len__()):
  data = {}
  data['type'] = 'Feature'
  #data['properties'] = {}
  data['properties'] = {
      'codigo_localidad': datos_df['codigo_localidad'].iloc[geo],
      'codigo_upz' : datos_df['codigo_upz'].iloc[geo],
      'nombre' : datos_df['nombre'].iloc[geo],
      'codigo_barrio' : datos_df['codigo_barrio'].iloc[geo]}
  #data['geometry'] = []
  #data['geometry'].append({
  #data['geometry'] = {
  #    'type': 'Polygon',
  #    'coordinates' : datos_df['geo_shape'].iloc[geo]}

  data['geometry'] = datos_df['geo_shape'].iloc[geo]
  data['id'] = datos_df['nombre'].iloc[geo]
  json_A['features'].append(data)

print(json_A.items)

print(json_A.__len__())

with open('ordenes_nuevo.json', 'w') as file:
    #json.dump(json_A, file, indent=4)
    json.dump(json_A, file)

import folium

archivo_json_2 = "ordenes_nuevo.json"

with open(archivo_json_2, 'r') as f:
    datos_json2 = json.load(f)

archivo_json_2.__len__()

m = folium.Map(location=[4.6214113,-74.0198998], zoom_start=10)

folium.Choropleth(
    geo_data=archivo_json_2,
    name="choropleth",
    data=None,
    columns= None,
    key_on= None,
    fill_opacity=0.7,
    line_opacity= 0.2,
    legend_name="emisiones por kt C02 ",
).add_to(m)

m